image: "ruby:2.3.1"

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: cowhub-server-api
  POSTGRES_PASSWORD: sitdownwhenitsraining

services:
  - postgres:latest

cache:
  paths:
    - vendor/ruby

stages:
  - test
  - deploy

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - 'which rsync || ( apt-get update -y && apt-get install -y rsync )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
  - ruby -v
  - gem install bundler --no-ri --no-rdoc
  - bundle install -j $(nproc) --path vendor
  - alias ssh="ssh -o StrictHostKeyChecking=no"

rubocop:
  stage: test
  script:
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rake db:setup db:migrate
    - bundle exec rspec

deploy:
  stage: deploy
  only:
    - feature/docker_deploy
  script:
    - rsync -avz . -e ssh root@cloud-vm-46-166.doc.ic.ac.uk:/app
    - ssh root@cloud-vm-46-166.doc.ic.ac.uk "/bin/bash -c /deploy.sh"
