image: "docker:latest"

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: cowhub-server-api
  POSTGRES_PASSWORD: sitdownwhenitsraining

stages:
  - test

before_script:
  - docker-compose -v
  - docker-compose run web bundle exec rake db:create

rubocop:
  stage: test
  script:
    - docker-compose run web npm run rubocop

rspec:
  stage: test
  script:
    - docker-compose run web npm run rspec
