image: "ruby:2.3.1"

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: cowhub-server-api
  POSTGRES_PASSWORD: sitdownwhenitsraining

services:
  - postgres:latest

cache:
  paths:
    - vendor/ruby

stages:
  - test
  - release
  - deploy


rubocop:
  stage: test
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - gem install bundler --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor
    - bundle exec rake db:setup db:migrate
    - bundle exec rspec


release:
  image: "gitlab/dind:latest"
  stage: release
  only:
    - master
  script:
    - docker login -u $DOCKER_USER -p $DOCKER_PASS
    - docker build -t cowhub/cowhub-server-api:latest .
    - docker push cowhub/cowhub-server-api


deploy:
  stage: deploy
  only:
    - master
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - 'which rsync || ( apt-get update -y && apt-get install -y rsync )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$GITLAB_DEPLOY_KEY")
    - rm -rf .ssh/known_hosts
    - rsync --stats --progress -avz . -e "ssh -o StrictHostKeyChecking=no" root@cloud-vm-46-166.doc.ic.ac.uk:/app --delete --exclude ".git"
    - ssh root@cloud-vm-46-166.doc.ic.ac.uk "/bin/bash -c /app/deploy.sh"
