image: "ruby:2.3.1"

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: cowhub-server-api
  POSTGRES_PASSWORD: sitdownwhenitsraining

services:
  - postgres:latest

cache:
  paths:
    - vendor/ruby

stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - ruby -v
    - gem install bundler --no-ri --no-rdoc
    - bundle install -j $(nproc) --path vendor

rubocop:
  stage: test
  script:
    - bundle exec rubocop

rspec:
  stage: test
  script:
    - bundle exec rake db:setup db:migrate
    - bundle exec rspec

deploy:
  stage: deploy
  image: docker:latest
  only:
    - feature/docker_deploy
  script:
    - docker build -t cowhub-server-api .
