image: "docker:latest"

services:
  - postgres:latest

stages:
  - test

before_script:
  - docker build -t cowhub-server-api .
  - docker run cowhub-server-api "bundle exec rake db:create"

rubocop:
  stage: test
  script:
    - docker info

rspec:
  stage: test
  script:
    - docker info

variables:
  RAILS_ENV: test
  POSTGRES_HOST: postgres
  POSTGRES_USER: cowhub-server-api
  POSTGRES_PASSWORD: sitdownwhenitsraining
