AllCops:
  Include:
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - node_modules/**/*
    - spec/*_helper.rb
    - vendor/**/*
    - Gemfile
Documentation:
  Enabled: false
Style/RedundantBegin:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 100
Metrics/LineLength:
  Max: 120
Metrics/CyclomaticComplexity:
  Max: 30
Metrics/PerceivedComplexity:
  Max: 30
MethodLength:
  Max: 30
BlockLength:
  Max: 200
Style/GlobalVars:
  AllowedVariables:
    - $s3
