AllCops:
  Include:
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - bin/**/*
    - node_modules/**/*
    - spec/*_helper.rb
    - vendor/**/*
    - Gemfile
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/AbcSize:
  Max: 25
Metrics/LineLength:
  Max: 120
MethodLength:
  Max: 30
