version: '2'

services:
  db:
    image: postgres
  mq:
    image: rabbitmq:3
  api:
    build: .
    command: /bin/bash -c "npm run db_setup && npm start"
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
      - RABBIT_HOST=mq
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - db
    depends_on:
      - db
      - mq
