version: '2'

services:
  db:
    image: postgres
  api:
    build: .
    command: /bin/bash -c "sleep 5 && bundle exec rake db:setup && rails s -p 8080"
    environment:
      - RAILS_ENV=development
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    links:
      - db
      - s3
    depends_on:
      - db
      - s3
  s3:
    image: lphoward/fake-s3
    volumes:
      - ./s3:/fakes3_root
