FROM ruby:2.3.1

RUN apt-get install -y --no-install-recommends postgresql-client \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

ENV RAILS_ENV production

COPY .ruby-version ./
COPY Gemfile* ./
RUN bundle install

COPY . .

EXPOSE 80
CMD [ "/bin/bash", "-c", "bundle exec rake db:migrate && bundle exec rails server -b 0.0.0.0 -p 80" ]
