default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { "localhost" } %>
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USER") { "cowhub-server-api" } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { "sitdownwhenitsraining" } %>

development:
  <<: *default
  database: cowhub-server-api_development

test:
  <<: *default
  database: cowhub-server-api_test

production:
  <<: *default
  database: cowhub-server-api_production
  password: "D8kKTVZBz/b8jxj32lTw8cvJaQ0FGrfytPc+rXh08PY="
