default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: <%= ENV.fetch("POSTGRES_USER") { 'cowhub-server-api' } %>
  password: <%= ENV.fetch("POSTGRES_PASSWORD") { 'sitdownwhenitsraining' } %>
  host: <%= ENV.fetch("POSTGRES_HOST") { 'localhost' } %>

development:
  <<: *default
  database: cowhub-server-api_development

test:
  <<: *default
  database: cowhub-server-api_test

production:
  <<: *default
  encoding: utf8
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
