default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: ubuntu
  timeout: 5000

production:
  <<: *default
  database: cowhub-server-api_production

development:
  <<: *default
  database: cowhub-server-api_development

test:
  <<: *default
  database: cowhub-server-api_test
